### ISSUE TITLE
Advanced skills don't create attribute

### ISSUE THREAD

**Issue by Maetco** [timothystone/roll20-character-sheets#9]
At the moment added advanced skills don't crate an attribute so no macros or token abilities can use their value.

**Comment by timothystone** [comment]
Well, @Maetco I wasn't ignoring this, but it really has been a year since you posted this, and I can't remember if we discussed the issue. Link to the roll20 forums if we did...

I'm also wondering, was this a limitation of Roll20? I think they fixed it.

**Comment by timothystone** [comment]
One of the roll20 issues was how repeating sections assigned attribute values in the underlying code, it was not easy to have a hidden value that would populate with an attribute you could use in macros. Recent changes are fixing that or have been fixed in recent release that would allow you to drag a repeating section to the macro bar. 

I don't know if it also addressed if I could create an underlying attribute for external macros.
